---
  extends: "eslint:recommended"
  root: true
  env:
    es6: true
    browser: true
    node: true
  ecmaFeatures:
    modules: false
  rules:
    brace-style:
      - 1
      - "1tbs"
    camelcase: 1
    comma-style:
      - 1
      - "first"
    comma-dangle: 2
    prefer-arrow-callback: 1
    no-console: 1
    complexity:
      - 1
      - 10
    curly:
      - 2
      - "multi-line"
    dot-notation:
      - 1
      -
        allowKeywords: true
    eqeqeq:
      - 1
      - "allow-null"
    strict: 0
    arrow-parens:
      - 1
      - as-needed
    guard-for-in: 2
    indent:
      - 1
      - 2
      - SwitchCase: 1
    no-mixed-spaces-and-tabs: 2
    max-depth:
      - 1
      - 3
    max-len:
      - 1
      - 120
      - 4
    max-params:
      - 1
      - 4
    max-statements:
      - 1
      - 10
    new-cap: 0
    no-bitwise: 1
    no-caller: 1
    no-cond-assign:
      - 1
      - "except-parens"
    no-debugger: 1
    no-empty: 2
    no-eval: 2
    no-extend-native: 2
    no-extra-parens:
      - 1
      - "functions"
    no-irregular-whitespace: 1
    no-iterator: 2
    no-loop-func: 2
    no-multi-str: 2
    no-new: 1
    no-var: 2
    no-plusplus:
      - 1
      -
        allowForLoopAfterthoughts: true
    no-proto: 1
    no-script-url: 1
    no-sequences: 2
    no-shadow: 2
    no-undef: 2
    no-unused-vars:
      - 1
      -
        argsIgnorePattern: "_"
    no-with: 2
    quotes:
      - 1
      - "single"
    semi:
      - 2
      - "never"
    no-extra-semi: 1
    valid-typeof: 1
    wrap-iife:
      - 1
      - "outside"
    arrow-spacing: 1
